version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "8082:8082"
    environment:
     - SERVERPORT=8082
     - JARVERSION=v1
    volumes:
     - .:/code
